---
- name: Fetch current user
  shell: whoami
  register: whoami
  changed_when: false

- name: Configure shell
  become: true
  user:
    name: "{{ whoami.stdout }}"
    shell: /bin/zsh

- name: Create ssh key pair
  user:
    name: "{{ whoami.stdout }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: "Add authorized keys"
  authorized_key:
    user: "{{ whoami.stdout }}"
    state: present
    key: "{{ lookup('file', key) }}"
  with_fileglob: files/{{ whoami.stdout }}.*.pub
  loop_control:
    loop_var: key

- name: Install xclip
  tags: gnome
  become: true
  package:
    name:
      - xclip

- name: Install yadm
  become: true
  package:
    name:
      - yadm

- name: Clone dotfiles repository
  shell: "[ -d $HOME/.yadm ] || yadm clone {{ lookup('env', 'DOTFILES_REPO') | default('https://github.com/cpollet/dotfiles.git', True) }}"

- name: Update dotfiles repository
  shell: "yadm pull"

- name: "Bootstrap yadm"
  shell: "$HOME/.config/yadm/bootstrap"

# todo move to base
- name: "Install fonts"
  include_tasks: "fonts.yml"
  tags: gnome

- name: Execute gnome tasks
  include_tasks: "gnome.yml"
  tags: gnome