---
- name: Fetch current user
  shell: whoami
  register: whoami
  changed_when: false

- name: Configure shell
  become: true
  user:
    name: "{{ whoami.stdout }}"
    shell: /bin/zsh

- name: Create ssh key pair
  user:
    name: "{{ whoami.stdout }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: "Add authorized keys"
  authorized_key:
    user: "{{ whoami.stdout }}"
    state: present
    key: "{{ lookup('file', key) }}"
  with_fileglob: files/{{ whoami.stdout }}.*.pub
  loop_control:
    loop_var: key

- name: Clone dotfiles
  git:
    repo: "{{ lookup('env', 'DOTFILES_REPO') | default('https://github.com/cpollet/dotfiles.git', True) }}"
    dest: ~/.dotfiles
    version: ansible
    update: yes

- name: Create tmp dir
  tempfile:
    state: directory
    suffix: _dotfiles
  register: dotfiles_dir

- name: Fetch dotfiles playbook
  fetch:
    src: ~/.dotfiles/ansible/local.yml
    dest: "{{ dotfiles_dir.path }}"
  changed_when: false

- name: Execute dotfiles playbook
  include_tasks: "{{ dotfiles_dir.path }}/localhost/home/{{ whoami.stdout }}/.dotfiles/ansible/local.yml"
  vars:
    tmp_dir: "{{ dotfiles_dir.path }}"
    current_user: "{{ whoami.stdout }}"

- name: Remove temp dir
  file:
    path: "{{ dotfiles_dir.path }}"
    state: absent
  when: dotfiles_dir.path is defined

