---
- name: Fetch current user
  shell: whoami
  register: whoami
  changed_when: false

- name: Configure shell
  become: true
  user:
    name: "{{ whoami.stdout }}"
    shell: /bin/zsh

# move to dotfiles
- name: Create ssh key pair
  user:
    name: "{{ whoami.stdout }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: "Add authorized keys"
  authorized_key:
    user: "{{ whoami.stdout }}"
    state: present
    key: "{{ lookup('file', key) }}"
  with_fileglob: files/{{ whoami.stdout }}.*.pub
  loop_control:
    loop_var: key

# todo move to base
- name: Install xclip
  tags: gnome
  become: true
  package:
    name:
      - xclip

- name: Check yadm
  stat:
    path: $HOME/.local/share/yadm/repo.git
  register: yadm
  changed_when: false

#- name: Dotfiles repository
#  debug:
#    msg: "{{ DOTFILES_REPO }}"
#  when: yadm.stat.exists == false
#  vars:
#    DOTFILES_REPO: "{{ lookup('env', 'DOTFILES_REPO') | default('https://github.com/cpollet/dotfiles.git', True) }}"

- name: Clone dotfiles repository
  shell: "echo 'source <(curl -L bootstrap.yadm.io) && cd $HOME && yadm clone {{ DOTFILES_REPO }} --bootstrap' | /bin/bash"
  when: yadm.stat.exists == false
  vars:
    DOTFILES_REPO: "{{ lookup('env', 'DOTFILES_REPO') | default('https://github.com/cpollet/dotfiles.git', True) }}"

# todo move to base
- name: "Install fonts"
  include_tasks: "fonts.yml"
  tags: gnome

- name: Execute gnome tasks
  include_tasks: "gnome.yml"
  tags: gnome
