---
- hosts: localhost
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: pre-run | upgrade all packages (ubuntu)
      tags: always
      apt: upgrade=dist
      when: ansible_distribution == "Ubuntu"

- hosts: localhost
  tags: base
  become: true
  roles:
    - base

- hosts: localhost
  tags: dev
  become: true
  roles:
    - dev

- hosts: localhost
  tags: profile
  become: false
  roles:
    - profile