---
# ref: https://github.com/nodesource/distributions/blob/master/README.md#debmanual
# ref: https://stackoverflow.com/a/45844178
- name: Install the gpg key for nodejs {{ NODEJS_VERSION }} LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs {{ NODEJS_VERSION }} LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodejs
    update_cache: yes

- name: Install nodejs {{ NODEJS_VERSION }} LTS
  apt:
    name: nodejs
    state: present
