---
# ref: https://developer.1password.com/docs/cli/get-started/

- name: Download 1password apt repository key
  get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: "/tmp/1password.asc"
  changed_when: false

- name: Add key for apt repository
  shell:
    cmd: cat /tmp/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Install 1password repos
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ deb_architecture.stdout }} stable main"
    state: present
    filename: 1password
    update_cache: yes

- name: Add the debsig-verify policy for 1password (1/4)
  file:
    path: /etc/debsig/policies/AC2D62742012EA22/
    state: directory

- name: Add the debsig-verify policy for 1password (2/4)
  get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: "/etc/debsig/policies/AC2D62742012EA22/1password.pol"

- name: Add the debsig-verify policy for 1password (3/4)
  file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory

- name: Add the debsig-verify policy for 1password (4/4)
  shell:
    cmd: cat /tmp/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: Install 1password
  package:
    name:
      - 1password-cli