---
- name: Install the gpg key for docker
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Install docker repos
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/v{{ DOCKER_COMPOSE_VERSION }}/docker-compose-linux-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Adding existing user {{ user }} to group docker
  user:
    name: "{{ user }}"
    groups: docker
    append: yes