---
- name: Create user accounts
  user:
    name: "{{ user_item }}"
  vars:
    user: "{{ user_item }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: user_item

- name: "Import ssh keys"
  include_tasks: import_ssh_keys.yml
  vars:
    user: "{{ user_item }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: user_item

