---
- name: install makepasswd package
  package:
    name:
      - makepasswd

- name: Create user accounts
  include_tasks: create_user.yml
  vars:
    user: "{{ user_item }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: user_item