---
- name: "Create user {{ user }}"
  user:
    state: present
    name: "{{ user }}"
  register: user_created

- name: Generate password for {{ user }}
  shell: makepasswd --chars=20
  register: user_password
  when: user_created.changed

- name: "Set password for {{ user }}"
  shell: echo {{ user }}:{{ user_password.stdout }} | chpasswd
  when: user_created.changed

- name: Force {{ user }} to change password
  shell: chage -d 0 {{ user }}
  when: user_created.changed

- name: Display password for {{ user }}
  debug: msg="Password for {{ user }} is {{ user_password.stdout }}"
  when: user_created.changed

- name: Add {{ user }} to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ user }}
    line: "{{ user }} ALL=(ALL) PASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'