---
- import_tasks: create_users.yml
  vars:
    users:
      - cpollet

- name: install packages
  package:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - aptitude
      - openssh-server
      - zsh
      - fish
      - git
      - curl
      - htop
      - vim
      - tmux
      - tree
      - pandoc
      - elinks
      - grc

- name: install custom scripts
  copy:
    src: mdless
    dest: /usr/local/bin/mdless
    owner: root
    group: root
    mode: '0755'

# todo move to dev
- name: install X packages
  package:
    name:
      - kdiff3
      - terminator
      - alacritty
  tags:
    - gnome

- import_tasks: software/docker.yml
  vars:
    DOCKER_COMPOSE_VERSION: "2.5.0"
    users:
      - cpollet