---
- name: install packages
  package:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - aptitude
      - openssh-server
      - zsh
      - git
      - curl
      - htop
      - vim
      - tmux

- import_tasks: software/docker.yml
  vars:
    DOCKER_COMPOSE_VERSION: "2.5.0"