---
- import_tasks: create_users.yml
  vars:
    users:
      - cpollet

- name: Add users to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ item }}
    line: "{{ item }} ALL=(ALL) PASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items:
    - cpollet

- name: install packages
  package:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - aptitude
      - openssh-server
      - zsh
      - git
      - curl
      - htop
      - vim
      - tmux

- import_tasks: software/docker.yml
  vars:
    DOCKER_COMPOSE_VERSION: "2.5.0"
    users:
      - cpollet