---
- import_tasks: create_users.yml
  vars:
    users:
      - cpollet

- name: install packages
  package:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - aptitude
      - openssh-server
      - zsh
      - fish
      - git
      - curl
      - htop
      - vim
      - tmux
      - tree
      - pandoc
      - elinks
      - grc

- name: install package (ubuntu >20.10)
  package:
    name:
      - exa
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_version == "20.10" or ansible_distribution_major_version | int > 20)
  register: exa_package

- name: install exa (ubuntu <20.10)
  import_tasks: software/exa.yml
  vars:
    EXA_VERSION: "v0.10.0"
  when: exa_package is skipped

- name: install custom scripts
  copy:
    src: mdless
    dest: /usr/local/bin/mdless
    owner: root
    group: root
    mode: '0755'

# todo move to dev
- name: install X packages
  package:
    name:
      - kdiff3
      - terminator
      - alacritty
  tags:
    - gnome

- import_tasks: software/docker.yml
  vars:
    DOCKER_COMPOSE_VERSION: "2.5.0"
    users:
      - cpollet