---
- import_tasks: create_users.yml
  vars:
    users:
      - cpollet

- name: install packages
  package:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - aptitude
      - openssh-server
      - zsh
      - fish
      - git
      - curl
      - htop
      - vim
      - tmux
      - tree
      - grc

- name: install package (ubuntu >20.10)
  package:
    name:
      - exa
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_version == "20.10" or ansible_distribution_major_version | int > 20)
  register: exa_package

- name: install exa (ubuntu <20.10)
  import_tasks: software/exa.yml
  vars:
    EXA_VERSION: "v0.10.0"
  when: exa_package is skipped

- name: install cbr
  copy:
    src: cbr
    dest: /usr/local/bin/cbr
    owner: root
    group: root
    mode: '0755'

- name: install cbw
  copy:
    src: cbw
    dest: /usr/local/bin/cbw
    owner: root
    group: root
    mode: '0755'

# todo move to dev
- name: install X packages
  package:
    name:
      - kdiff3
      - terminator
  tags:
    - gnome

- name: Install alacritty (ubuntu >18.04)
  package:
    name:
      - alacritty
  tags:
    - gnome
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_version == "18.10" or ansible_distribution_major_version | int > 19)
  register: alacritty_package

- name: Install alacritty (ubuntu <18.10)
  import_tasks: software/alacritty.yml
  tags:
    - gnome
  when: alacritty_package is skipped

- import_tasks: software/docker.yml
  vars:
    DOCKER_COMPOSE_VERSION: "2.5.0"
    users:
      - cpollet

- name: Install glow (markdown cli viewer)
  import_tasks:  software/glow.yml
  vars:
    GLOW_VERSION: "1.4.1"

# todo ubuntu 18.10+: check what's in package...
- name: Install fzf
  import_tasks:  software/fzf.yml
  vars:
    FZF_VERSION: "0.30.0"

- name: Install delta (colorful diff)
  import_tasks:  software/delta.yml
  vars:
    DELTA_VERSION: "0.13.0"

- name: Install bat (cat clone with wings)
  import_tasks:  software/bat.yml
  vars:
    BAT_VERSION: "0.21.0"

- name: Install fx (less for json)
  import_tasks: software/fx.yml
  vars:
    FX_VERSION: "24.0.0"

- name: Install 1password
  import_tasks: software/1password.yml